import type { ActivityDocument } from '../activity/contracts'
import type { FeedDocument } from './contracts'
import type { PolicyDocument } from '../policy/contracts'
import type { NotificationSettings } from '../notify/contracts'

/** Shared demo fixtures — also imported by docs workbenches. */

export const DEMO_FEED: FeedDocument = {
  schemaVersion: '1',
  id: 'feed-demo',
  revision: 'r1',
  metadata: {},
  sources: [
    {
      id: 'src-misskatie',
      handle: 'misskatie',
      url: 'https://youtube.com/@misskatie',
      platform: 'youtube',
      workflowName: 'youtube-poll',
      health: 'healthy',
      unreadCount: 2,
      credentialRef: 'cred_yt_demo',
    },
    {
      id: 'src-k2s',
      handle: 'k2s.cc/domain',
      url: 'https://k2s.cc/file/example',
      platform: 'web',
      workflowName: 'k2s-unlock',
      health: 'unreachable',
      unreadCount: 1,
      credentialRef: 'cred_k2s_demo',
    },
    {
      id: 'src-lobsters',
      handle: 'lobste.rs',
      url: 'https://lobste.rs/rss',
      platform: 'rss',
      workflowName: 'rss-poll',
      health: 'healthy',
      unreadCount: 3,
    },
  ],
  entries: [
    {
      id: 'entry-mk-1',
      sourceId: 'src-misskatie',
      title: 'MissKatie — Spring Lookbook',
      url: 'https://youtube.com/watch?v=mk1',
      publishedAt: '2026-08-18T14:00:00.000Z',
      excerpt: 'New spring looks, soft light, and a bonus B-roll pack for patrons.',
      tags: ['release', 'fashion'],
      readState: 'unread',
      contentKind: 'video',
      artifactStatus: 'ready',
      media: { kind: 'image', url: '/images/placeholder-video.svg', width: 640, height: 360 },
      body: 'Full lookbook notes.\n\nSoft daylight, linen textures, and a short narration track you can cache offline.',
    },
    {
      id: 'entry-mk-2',
      sourceId: 'src-misskatie',
      title: 'MissKatie — Q&A stream recap',
      url: 'https://youtube.com/watch?v=mk2',
      publishedAt: '2026-08-10T18:30:00.000Z',
      excerpt: 'Highlights from last week’s live Q&A.',
      tags: ['stream'],
      readState: 'read',
      contentKind: 'video',
      artifactStatus: 'none',
      body: 'Recap chapters and links from the stream.',
    },
    {
      id: 'entry-k2s-1',
      sourceId: 'src-k2s',
      title: 'Token drop: aurora-pack.zip',
      url: 'https://k2s.cc/file/aurora-pack',
      publishedAt: '2026-08-19T09:12:00.000Z',
      excerpt: 'Limited token unlock for aurora-pack.zip on the watched domain.',
      tags: ['token', 'release'],
      readState: 'unread',
      contentKind: 'release',
      artifactStatus: 'queued',
      body: 'Host will queue k2s-unlock → validate → library ingest when policy says auto_queue.',
    },
    {
      id: 'entry-lob-1',
      sourceId: 'src-lobsters',
      title: 'Readable RSS clients still matter',
      url: 'https://lobste.rs/s/demo1',
      publishedAt: '2026-08-19T16:00:00.000Z',
      excerpt: 'A short thread on feed readers versus algorithmic timelines.',
      tags: ['rss', 'ux'],
      readState: 'unread',
      contentKind: 'article',
      artifactStatus: 'ready',
      body: 'Feeds keep the reading list honest. Algorithms optimize for dwell; RSS optimizes for intent.',
    },
    {
      id: 'entry-lob-2',
      sourceId: 'src-lobsters',
      title: 'Sandboxing guest Lua without a browser VM',
      url: 'https://lobste.rs/s/demo2',
      publishedAt: '2026-08-17T11:00:00.000Z',
      excerpt: 'Keep policy scripts on the host; highlight them in the UI.',
      tags: ['lua', 'security'],
      readState: 'unread',
      contentKind: 'article',
      body: 'Edit and highlight Lua in the client. Execute it in a constrained host runtime.',
    },
  ],
  matches: [
    {
      entryId: 'entry-mk-1',
      policyId: 'pol-mk-cache',
      disposition: 'notify_and_cache',
      matchedAt: '2026-08-18T14:05:00.000Z',
    },
    {
      entryId: 'entry-k2s-1',
      policyId: 'pol-k2s-auto',
      disposition: 'auto_queue',
      matchedAt: '2026-08-19T09:15:00.000Z',
    },
  ],
}

export const DEMO_POLICY: PolicyDocument = {
  schemaVersion: '1',
  id: 'policy-demo',
  revision: 'r1',
  metadata: {},
  rules: [
    {
      id: 'pol-mk-cache',
      sourceId: 'src-misskatie',
      name: 'Notify + cache on release',
      enabled: true,
      criteria: {
        mode: 'builder',
        clauses: [
          {
            id: 'c1',
            field: 'tags',
            operator: 'includes_tag',
            value: 'release',
          },
        ],
      },
      disposition: 'notify_and_cache',
      workflowEdge: 'notify',
      matchCount: 1,
      lastMatchAt: '2026-08-18T14:05:00.000Z',
    },
    {
      id: 'pol-k2s-auto',
      sourceId: 'src-k2s',
      name: 'Auto-queue token drops',
      enabled: true,
      criteria: {
        mode: 'builder',
        clauses: [
          { id: 'c1', field: 'title', operator: 'contains', value: 'token' },
          { id: 'c2', field: 'contentKind', operator: 'equals', value: 'release' },
        ],
      },
      disposition: 'auto_queue',
      workflowEdge: 'intent_create',
      matchCount: 1,
      lastMatchAt: '2026-08-19T09:15:00.000Z',
    },
    {
      id: 'pol-lua-sample',
      sourceId: 'src-lobsters',
      name: 'Lua escape hatch (docs only)',
      enabled: true,
      criteria: {
        mode: 'lua',
        source: `-- Demo only: not executed in the browser\nreturn entry.title:find("RSS") ~= nil`,
      },
      disposition: 'notify_only',
      workflowEdge: 'notify',
      matchCount: 0,
    },
  ],
}

export const DEMO_NOTIFY_SETTINGS: NotificationSettings = {
  defaultChannel: 'instant',
  bySource: { 'src-lobsters': 'digest' },
  byPolicy: {},
  quietHours: null,
}

export const DEMO_ACTIVITY: ActivityDocument = {
  schemaVersion: '1',
  id: 'activity-demo',
  revision: 'r1',
  metadata: {},
  events: [
    {
      id: 'act-1',
      title: 'Token drop: aurora-pack.zip matched auto_queue',
      href: '#/components/feed?entry=entry-k2s-1',
      publishedAt: '2026-08-19T09:15:00.000Z',
      signals: ['hot', 'intent', 'notify'],
      score: 240,
      commentCount: 18,
      shareCount: 6,
      attribution: 'k2s.cc/domain · policy pol-k2s-auto',
      sourceId: 'src-k2s',
      entryId: 'entry-k2s-1',
      threadId: 'thread-aurora',
    },
    {
      id: 'act-2',
      title: 'MissKatie — Spring Lookbook cached',
      href: '#/components/feed?entry=entry-mk-1',
      publishedAt: '2026-08-18T14:05:00.000Z',
      signals: ['artifact', 'notify'],
      score: 120,
      commentCount: 4,
      shareCount: 2,
      attribution: 'misskatie · notify_and_cache',
      sourceId: 'src-misskatie',
      entryId: 'entry-mk-1',
    },
    {
      id: 'act-3',
      title: 'Readable RSS clients still matter',
      href: '#/components/activity?thread=thread-rss',
      publishedAt: '2026-08-19T16:05:00.000Z',
      signals: ['new', 'rising'],
      score: 88,
      commentCount: 32,
      shareCount: 11,
      attribution: 'lobste.rs · via Level1Techs cross-post',
      sourceId: 'src-lobsters',
      entryId: 'entry-lob-1',
      threadId: 'thread-rss',
    },
    {
      id: 'act-4',
      title: 'Sandboxing guest Lua without a browser VM',
      href: '#/components/policy',
      publishedAt: '2026-08-17T11:10:00.000Z',
      signals: ['top'],
      score: 310,
      commentCount: 54,
      shareCount: 20,
      attribution: 'lobste.rs',
      sourceId: 'src-lobsters',
      entryId: 'entry-lob-2',
    },
  ],
  channels: [
    { id: 'ch-general', name: 'General', slug: 'general' },
    { id: 'ch-media', name: 'Media', slug: 'media' },
  ],
  threads: [
    {
      id: 'thread-aurora',
      channelId: 'ch-media',
      title: 'aurora-pack.zip unlock thread',
      createdAt: '2026-08-19T09:20:00.000Z',
      replyCount: 3,
    },
    {
      id: 'thread-rss',
      channelId: 'ch-general',
      title: 'RSS clients vs algorithms',
      createdAt: '2026-08-19T16:10:00.000Z',
      replyCount: 2,
    },
  ],
  posts: [
    {
      id: 'post-a1',
      threadId: 'thread-aurora',
      author: 'ops',
      createdAt: '2026-08-19T09:20:00.000Z',
      body: 'Policy matched; intent queued for k2s-unlock.',
      depth: 0,
    },
    {
      id: 'post-a2',
      threadId: 'thread-aurora',
      author: 'maya',
      createdAt: '2026-08-19T09:22:00.000Z',
      body: 'Confirming credentialRef cred_k2s_demo — no raw token in chat.',
      depth: 1,
    },
    {
      id: 'post-a3',
      threadId: 'thread-aurora',
      author: 'ops',
      createdAt: '2026-08-19T09:25:00.000Z',
      body: 'Validate step green; library ingest next.',
      depth: 1,
    },
    {
      id: 'post-r1',
      threadId: 'thread-rss',
      author: 'reader',
      createdAt: '2026-08-19T16:10:00.000Z',
      body: 'Keep the subscriptions page for reading; keep Activity for heat.',
      depth: 0,
    },
    {
      id: 'post-r2',
      threadId: 'thread-rss',
      author: 'maya',
      createdAt: '2026-08-19T16:12:00.000Z',
      body: 'Agreed — two nav pages, not one density toggle.',
      depth: 1,
    },
  ],
  crossPosts: [
    {
      id: 'xp-1',
      fromThreadId: 'thread-rss',
      toThreadId: 'thread-aurora',
      note: 'Related: token drops also show up in Activity heat.',
    },
  ],
}
