/**
 * Hand-authored mock fixtures for independent tint client work.
 * URLs may look real; nothing is fetched at runtime.
 */

import type { ActivityDocument } from '../activity/contracts'
import type { FeedDocument } from './contracts'
import type { PolicyDocument } from '../policy/contracts'
import type { NotificationSettings } from '../notify/contracts'

export const DEMO_FEED: FeedDocument = {
  schemaVersion: '1',
  id: 'feed-demo',
  revision: 'r1',
  metadata: { mock: true },
  channels: [
    {
      id: 'ch-misskatie',
      slug: 'misskatie',
      name: 'MissKatie',
      description: 'Creator room — multi-platform fan-out',
    },
    {
      id: 'ch-ltt',
      slug: 'LTT',
      name: 'LinusTechTips',
      description: 'Org room — YouTube, Reddit, TikTok',
    },
    {
      id: 'ch-gaming',
      slug: 'gaming',
      name: 'Gaming',
      description: 'Topic room aggregating mixed streams',
    },
    {
      id: 'ch-nsfw',
      slug: 'nsfw',
      name: 'NSFW',
      description: 'Topic room — placeholder tags only, no media',
    },
    {
      id: 'ch-lobsters',
      slug: 'lobsters',
      name: 'Lobsters',
      description: 'Classic single-stream RSS room',
    },
    {
      id: 'ch-k2s',
      slug: 'k2s',
      name: 'k2s',
      description: 'Maya auto_queue demo room',
    },
  ],
  sources: [
    {
      id: 'src-mk-yt',
      channelId: 'ch-misskatie',
      handle: '@misskatie',
      url: 'https://youtube.com/@misskatie',
      platform: 'youtube',
      workflowName: 'youtube-poll',
      health: 'healthy',
      unreadCount: 2,
      credentialRef: 'cred_yt_demo',
    },
    {
      id: 'src-mk-tt',
      channelId: 'ch-misskatie',
      handle: '@misskatie',
      url: 'https://tiktok.com/@misskatie',
      platform: 'tiktok',
      workflowName: 'tiktok-poll',
      health: 'healthy',
      unreadCount: 1,
    },
    {
      id: 'src-mk-ig',
      channelId: 'ch-misskatie',
      handle: '@misskatie',
      url: 'https://instagram.com/misskatie',
      platform: 'instagram',
      workflowName: 'instagram-poll',
      health: 'healthy',
      unreadCount: 1,
    },
    {
      id: 'src-ltt-yt',
      channelId: 'ch-ltt',
      handle: 'LinusTechTips',
      url: 'https://youtube.com/@LinusTechTips',
      platform: 'youtube',
      workflowName: 'youtube-poll',
      health: 'healthy',
      unreadCount: 1,
    },
    {
      id: 'src-ltt-reddit',
      channelId: 'ch-ltt',
      handle: 'r/linustechtips',
      url: 'https://reddit.com/r/linustechtips',
      platform: 'reddit',
      workflowName: 'reddit-poll',
      health: 'healthy',
      unreadCount: 1,
    },
    {
      id: 'src-ltt-tt',
      channelId: 'ch-ltt',
      handle: '@linustechtips',
      url: 'https://tiktok.com/@linustechtips',
      platform: 'tiktok',
      workflowName: 'tiktok-poll',
      health: 'inactive',
      unreadCount: 0,
    },
    {
      id: 'src-gaming-yt',
      channelId: 'ch-gaming',
      handle: 'GameTech',
      url: 'https://youtube.com/@GameTechDemo',
      platform: 'youtube',
      workflowName: 'youtube-poll',
      health: 'healthy',
      unreadCount: 1,
    },
    {
      id: 'src-gaming-rss',
      channelId: 'ch-gaming',
      handle: 'gaming-weekly',
      url: 'https://example.com/feeds/gaming.rss',
      platform: 'rss',
      workflowName: 'rss-poll',
      health: 'healthy',
      unreadCount: 1,
    },
    {
      id: 'src-nsfw-rss',
      channelId: 'ch-nsfw',
      handle: 'nsfw-digest',
      url: 'https://example.com/feeds/nsfw.rss',
      platform: 'rss',
      workflowName: 'rss-poll',
      health: 'dormant',
      unreadCount: 0,
    },
    {
      id: 'src-lobsters',
      channelId: 'ch-lobsters',
      handle: 'lobste.rs',
      url: 'https://lobste.rs/rss',
      platform: 'rss',
      workflowName: 'rss-poll',
      health: 'healthy',
      unreadCount: 2,
    },
    {
      id: 'src-k2s',
      channelId: 'ch-k2s',
      handle: 'k2s.cc/domain',
      url: 'https://k2s.cc/file/example',
      platform: 'web',
      workflowName: 'k2s-unlock',
      health: 'unreachable',
      unreadCount: 1,
      credentialRef: 'cred_k2s_demo',
    },
  ],
  entries: [
    // MissKatie · YouTube
    {
      id: 'entry-mk-yt-1',
      sourceId: 'src-mk-yt',
      title: 'MissKatie — Spring Lookbook',
      url: 'https://youtube.com/watch?v=mk1',
      publishedAt: '2026-08-18T14:00:00.000Z',
      excerpt: 'New spring looks, soft light, and a bonus B-roll pack for patrons.',
      tags: ['release', 'fashion'],
      readState: 'unread',
      contentKind: 'video',
      artifactStatus: 'ready',
      media: { kind: 'image', url: '/images/placeholder-video.svg', width: 640, height: 360 },
      body: 'Full lookbook notes.\n\nSoft daylight, linen textures, and a short narration track you can cache offline.',
    },
    {
      id: 'entry-mk-yt-2',
      sourceId: 'src-mk-yt',
      title: 'MissKatie — Q&A stream recap',
      url: 'https://youtube.com/watch?v=mk2',
      publishedAt: '2026-08-10T18:30:00.000Z',
      excerpt: 'Highlights from last week’s live Q&A.',
      tags: ['stream'],
      readState: 'read',
      contentKind: 'video',
      artifactStatus: 'none',
      body: 'Recap chapters and links from the stream.',
    },
    {
      id: 'entry-mk-yt-3',
      sourceId: 'src-mk-yt',
      title: 'MissKatie — Desk setup tour',
      url: 'https://youtube.com/watch?v=mk3',
      publishedAt: '2026-08-16T12:00:00.000Z',
      excerpt: 'Lights, camera, and the cable that still won’t sit still.',
      tags: ['vlog'],
      readState: 'unread',
      contentKind: 'video',
      media: { kind: 'image', url: '/images/placeholder-video.svg', width: 640, height: 360 },
      body: 'Tour chapters with timestamps for the lighting rack and audio chain.',
    },
    // MissKatie · TikTok
    {
      id: 'entry-mk-tt-1',
      sourceId: 'src-mk-tt',
      title: '15s: linen jacket transition',
      url: 'https://tiktok.com/@misskatie/video/tt1',
      publishedAt: '2026-08-19T08:00:00.000Z',
      excerpt: 'Short-form cut from the lookbook B-roll.',
      tags: ['short', 'fashion'],
      readState: 'unread',
      contentKind: 'video',
      body: 'Vertical crop of the spring lookbook transition.',
    },
    {
      id: 'entry-mk-tt-2',
      sourceId: 'src-mk-tt',
      title: 'Quick tip: softbox height',
      url: 'https://tiktok.com/@misskatie/video/tt2',
      publishedAt: '2026-08-12T09:00:00.000Z',
      excerpt: 'Raise it until the catchlight sits right.',
      tags: ['tip'],
      readState: 'read',
      contentKind: 'video',
      body: 'Lighting tip clipped from the desk tour.',
    },
    // MissKatie · Instagram
    {
      id: 'entry-mk-ig-1',
      sourceId: 'src-mk-ig',
      title: 'Carousel: fabric swatches',
      url: 'https://instagram.com/p/ig1',
      publishedAt: '2026-08-17T15:00:00.000Z',
      excerpt: 'Three slides — linen, cotton, silk.',
      tags: ['carousel', 'fashion'],
      readState: 'unread',
      contentKind: 'other',
      body: 'Mock carousel caption. No remote images loaded.',
    },
    // LTT · YouTube
    {
      id: 'entry-ltt-yt-1',
      sourceId: 'src-ltt-yt',
      title: 'We built a quieter NAS',
      url: 'https://youtube.com/watch?v=ltt1',
      publishedAt: '2026-08-19T17:00:00.000Z',
      excerpt: 'Acoustic foam, better PSUs, and a spreadsheet of dB readings.',
      tags: ['hardware', 'nas'],
      readState: 'unread',
      contentKind: 'video',
      media: { kind: 'image', url: '/images/placeholder-video.svg', width: 640, height: 360 },
      body: 'Chapters: foam layout, PSU swap, before/after meters.',
    },
    {
      id: 'entry-ltt-yt-2',
      sourceId: 'src-ltt-yt',
      title: 'WAN show: floatplane notes',
      url: 'https://youtube.com/watch?v=ltt2',
      publishedAt: '2026-08-15T01:00:00.000Z',
      excerpt: 'Recap of the week’s tech headlines.',
      tags: ['wan'],
      readState: 'read',
      contentKind: 'video',
      body: 'Timestamped headline roundup.',
    },
    // LTT · Reddit
    {
      id: 'entry-ltt-rd-1',
      sourceId: 'src-ltt-reddit',
      title: 'PSA: NAS foam placement diagram',
      url: 'https://reddit.com/r/linustechtips/comments/demo1',
      publishedAt: '2026-08-19T18:30:00.000Z',
      excerpt: 'Community thread expanding on the quieter NAS video.',
      tags: ['discussion'],
      readState: 'unread',
      contentKind: 'thread',
      body: 'OP posted measurements. Top comment argues for rubber feet first.',
    },
    // LTT · TikTok (read, inactive source)
    {
      id: 'entry-ltt-tt-1',
      sourceId: 'src-ltt-tt',
      title: 'Cable-management speedrun',
      url: 'https://tiktok.com/@linustechtips/video/ltt1',
      publishedAt: '2026-08-01T12:00:00.000Z',
      excerpt: 'Thirty seconds of Velcro and regret.',
      tags: ['short'],
      readState: 'read',
      contentKind: 'video',
      body: 'Short clip; source marked inactive in the mock.',
    },
    // Gaming topic
    {
      id: 'entry-game-yt-1',
      sourceId: 'src-gaming-yt',
      title: 'Patch notes explained — season drop',
      url: 'https://youtube.com/watch?v=game1',
      publishedAt: '2026-08-18T20:00:00.000Z',
      excerpt: 'What actually changed in matchmaking.',
      tags: ['games', 'patch'],
      readState: 'unread',
      contentKind: 'video',
      body: 'Topic-room entry from a gaming YouTube stream.',
    },
    {
      id: 'entry-game-rss-1',
      sourceId: 'src-gaming-rss',
      title: 'Weekly: indie demos worth your weekend',
      url: 'https://example.com/gaming/weekly-1',
      publishedAt: '2026-08-19T11:00:00.000Z',
      excerpt: 'Five builds, one controller warning.',
      tags: ['indie', 'rss'],
      readState: 'unread',
      contentKind: 'article',
      body: 'RSS item aggregated into channel/gaming.',
    },
    // NSFW topic — tags only
    {
      id: 'entry-nsfw-1',
      sourceId: 'src-nsfw-rss',
      title: 'Policy reminder: tagged rooms stay behind filters',
      url: 'https://example.com/nsfw/policy',
      publishedAt: '2026-08-05T10:00:00.000Z',
      excerpt: 'Placeholder entry — no media, tags only.',
      tags: ['nsfw', 'policy'],
      readState: 'archived',
      contentKind: 'article',
      body: 'Mock NSFW room content stays textual for the tint client demo.',
    },
    // Lobsters RSS
    {
      id: 'entry-lob-1',
      sourceId: 'src-lobsters',
      title: 'Readable RSS clients still matter',
      url: 'https://lobste.rs/s/demo1',
      publishedAt: '2026-08-19T16:00:00.000Z',
      excerpt: 'A short thread on feed readers versus algorithmic timelines.',
      tags: ['rss', 'ux'],
      readState: 'unread',
      contentKind: 'article',
      artifactStatus: 'ready',
      body: 'Feeds keep the reading list honest. Algorithms optimize for dwell; RSS optimizes for intent.',
    },
    {
      id: 'entry-lob-2',
      sourceId: 'src-lobsters',
      title: 'Sandboxing guest Lua without a browser VM',
      url: 'https://lobste.rs/s/demo2',
      publishedAt: '2026-08-17T11:00:00.000Z',
      excerpt: 'Keep policy scripts on the host; highlight them in the UI.',
      tags: ['lua', 'security'],
      readState: 'unread',
      contentKind: 'article',
      body: 'Edit and highlight Lua in the client. Execute it in a constrained host runtime.',
    },
    {
      id: 'entry-lob-3',
      sourceId: 'src-lobsters',
      title: 'Channel rooms vs flat subscription lists',
      url: 'https://lobste.rs/s/demo3',
      publishedAt: '2026-08-14T09:00:00.000Z',
      excerpt: 'Topic rooms that own multiple platform streams.',
      tags: ['design'],
      readState: 'read',
      contentKind: 'article',
      body: 'One routeable channel; many inbound sources.',
    },
    // k2s
    {
      id: 'entry-k2s-1',
      sourceId: 'src-k2s',
      title: 'Token drop: aurora-pack.zip',
      url: 'https://k2s.cc/file/aurora-pack',
      publishedAt: '2026-08-19T09:12:00.000Z',
      excerpt: 'Limited token unlock for aurora-pack.zip on the watched domain.',
      tags: ['token', 'release'],
      readState: 'unread',
      contentKind: 'release',
      artifactStatus: 'queued',
      body: 'Host will queue k2s-unlock → validate → library ingest when policy says auto_queue.',
    },
  ],
  matches: [
    {
      entryId: 'entry-mk-yt-1',
      policyId: 'pol-mk-cache',
      disposition: 'notify_and_cache',
      matchedAt: '2026-08-18T14:05:00.000Z',
    },
    {
      entryId: 'entry-k2s-1',
      policyId: 'pol-k2s-auto',
      disposition: 'auto_queue',
      matchedAt: '2026-08-19T09:15:00.000Z',
    },
    {
      entryId: 'entry-game-rss-1',
      policyId: 'pol-lua-sample',
      disposition: 'notify_only',
      matchedAt: '2026-08-19T11:05:00.000Z',
    },
  ],
}

export const DEMO_POLICY: PolicyDocument = {
  schemaVersion: '1',
  id: 'policy-demo',
  revision: 'r1',
  metadata: {},
  rules: [
    {
      id: 'pol-mk-cache',
      sourceId: 'src-mk-yt',
      name: 'Notify + cache on release',
      enabled: true,
      criteria: {
        mode: 'builder',
        clauses: [
          {
            id: 'c1',
            field: 'tags',
            operator: 'includes_tag',
            value: 'release',
          },
        ],
      },
      disposition: 'notify_and_cache',
      workflowEdge: 'notify',
      matchCount: 1,
      lastMatchAt: '2026-08-18T14:05:00.000Z',
    },
    {
      id: 'pol-k2s-auto',
      sourceId: 'src-k2s',
      name: 'Auto-queue token drops',
      enabled: true,
      criteria: {
        mode: 'builder',
        clauses: [
          { id: 'c1', field: 'title', operator: 'contains', value: 'token' },
          { id: 'c2', field: 'contentKind', operator: 'equals', value: 'release' },
        ],
      },
      disposition: 'auto_queue',
      workflowEdge: 'intent_create',
      matchCount: 1,
      lastMatchAt: '2026-08-19T09:15:00.000Z',
    },
    {
      id: 'pol-lua-sample',
      sourceId: 'src-lobsters',
      name: 'Lua escape hatch (docs only)',
      enabled: true,
      criteria: {
        mode: 'lua',
        source: `-- Demo only: not executed in the browser\nreturn entry.title:find("RSS") ~= nil`,
      },
      disposition: 'notify_only',
      workflowEdge: 'notify',
      matchCount: 0,
    },
  ],
}

export const DEMO_NOTIFY_SETTINGS: NotificationSettings = {
  defaultChannel: 'instant',
  bySource: { 'src-lobsters': 'digest', 'src-nsfw-rss': 'off' },
  byPolicy: {},
  quietHours: null,
}

export const DEMO_ACTIVITY: ActivityDocument = {
  schemaVersion: '1',
  id: 'activity-demo',
  revision: 'r1',
  metadata: {},
  events: [
    {
      id: 'act-1',
      title: 'Token drop: aurora-pack.zip matched auto_queue',
      href: '#/components/feed?entry=entry-k2s-1',
      publishedAt: '2026-08-19T09:15:00.000Z',
      signals: ['hot', 'intent', 'notify'],
      score: 240,
      commentCount: 18,
      shareCount: 6,
      attribution: 'k2s · web',
      sourceId: 'src-k2s',
      entryId: 'entry-k2s-1',
      threadId: 'thread-aurora',
    },
    {
      id: 'act-2',
      title: 'MissKatie — Spring Lookbook cached',
      href: '#/components/feed?entry=entry-mk-yt-1',
      publishedAt: '2026-08-18T14:05:00.000Z',
      signals: ['artifact', 'notify'],
      score: 120,
      commentCount: 4,
      shareCount: 2,
      attribution: 'MissKatie · youtube',
      sourceId: 'src-mk-yt',
      entryId: 'entry-mk-yt-1',
    },
    {
      id: 'act-3',
      title: 'Weekly: indie demos worth your weekend',
      href: '#/components/activity?thread=thread-gaming',
      publishedAt: '2026-08-19T11:10:00.000Z',
      signals: ['new', 'rising'],
      score: 88,
      commentCount: 12,
      shareCount: 5,
      attribution: 'Gaming · rss',
      sourceId: 'src-gaming-rss',
      entryId: 'entry-game-rss-1',
      threadId: 'thread-gaming',
    },
    {
      id: 'act-4',
      title: 'Readable RSS clients still matter',
      href: '#/components/activity?thread=thread-rss',
      publishedAt: '2026-08-19T16:05:00.000Z',
      signals: ['new', 'rising'],
      score: 96,
      commentCount: 32,
      shareCount: 11,
      attribution: 'Lobsters · rss',
      sourceId: 'src-lobsters',
      entryId: 'entry-lob-1',
      threadId: 'thread-rss',
    },
    {
      id: 'act-5',
      title: 'Sandboxing guest Lua without a browser VM',
      href: '#/components/policy',
      publishedAt: '2026-08-17T11:10:00.000Z',
      signals: ['top'],
      score: 310,
      commentCount: 54,
      shareCount: 20,
      attribution: 'Lobsters · rss',
      sourceId: 'src-lobsters',
      entryId: 'entry-lob-2',
    },
    {
      id: 'act-6',
      title: 'We built a quieter NAS',
      href: '#/components/feed?entry=entry-ltt-yt-1',
      publishedAt: '2026-08-19T17:05:00.000Z',
      signals: ['hot'],
      score: 180,
      commentCount: 22,
      shareCount: 9,
      attribution: 'LinusTechTips · youtube',
      sourceId: 'src-ltt-yt',
      entryId: 'entry-ltt-yt-1',
    },
  ],
  // Same ids/slugs as feed channels where threads live in those rooms.
  channels: [
    { id: 'ch-gaming', name: 'Gaming', slug: 'gaming' },
    { id: 'ch-lobsters', name: 'Lobsters', slug: 'lobsters' },
    { id: 'ch-k2s', name: 'k2s', slug: 'k2s' },
    { id: 'ch-misskatie', name: 'MissKatie', slug: 'misskatie' },
  ],
  threads: [
    {
      id: 'thread-aurora',
      channelId: 'ch-k2s',
      title: 'aurora-pack.zip unlock thread',
      createdAt: '2026-08-19T09:20:00.000Z',
      replyCount: 3,
    },
    {
      id: 'thread-rss',
      channelId: 'ch-lobsters',
      title: 'RSS clients vs algorithms',
      createdAt: '2026-08-19T16:10:00.000Z',
      replyCount: 2,
    },
    {
      id: 'thread-gaming',
      channelId: 'ch-gaming',
      title: 'Indie demos this week',
      createdAt: '2026-08-19T11:15:00.000Z',
      replyCount: 2,
    },
  ],
  posts: [
    {
      id: 'post-a1',
      threadId: 'thread-aurora',
      author: 'ops',
      createdAt: '2026-08-19T09:20:00.000Z',
      body: 'Policy matched; intent queued for k2s-unlock.',
      depth: 0,
    },
    {
      id: 'post-a2',
      threadId: 'thread-aurora',
      author: 'maya',
      createdAt: '2026-08-19T09:22:00.000Z',
      body: 'Confirming credentialRef cred_k2s_demo — no raw token in chat.',
      depth: 1,
    },
    {
      id: 'post-a3',
      threadId: 'thread-aurora',
      author: 'ops',
      createdAt: '2026-08-19T09:25:00.000Z',
      body: 'Validate step green; library ingest next.',
      depth: 1,
    },
    {
      id: 'post-r1',
      threadId: 'thread-rss',
      author: 'reader',
      createdAt: '2026-08-19T16:10:00.000Z',
      body: 'Keep subscriptions for reading; keep Activity for heat.',
      depth: 0,
    },
    {
      id: 'post-r2',
      threadId: 'thread-rss',
      author: 'maya',
      createdAt: '2026-08-19T16:12:00.000Z',
      body: 'Agreed — channel rooms own streams; Activity ranks events.',
      depth: 1,
    },
    {
      id: 'post-g1',
      threadId: 'thread-gaming',
      author: 'player',
      createdAt: '2026-08-19T11:15:00.000Z',
      body: 'channel/gaming pulled both the YT explain and the RSS weekly.',
      depth: 0,
    },
    {
      id: 'post-g2',
      threadId: 'thread-gaming',
      author: 'maya',
      createdAt: '2026-08-19T11:18:00.000Z',
      body: 'Same Channel id as the feed room — forum expansion reuses the slug.',
      depth: 1,
    },
  ],
  crossPosts: [
    {
      id: 'xp-1',
      fromThreadId: 'thread-rss',
      toThreadId: 'thread-gaming',
      note: 'Topic rooms also show up in Activity heat.',
    },
  ],
}
