// GENERATED by scripts/vault-tasks.mjs - do not edit by hand.
// Window 2026-08-23 to 2026-09-05; 56 open items from 7 notes.
// Regenerate: node scripts/vault-tasks.mjs

import type { BoardDocument } from '../../components/board'

/** What a task card carries back to the note it came from. */
export type BoardTaskPayload = {
  sourceNote: string
  sourceLine: number
  date: string
  section: string
  tags: readonly string[]
  links: readonly string[]
  raw: string
}

export const VAULT_TASK_BOARD: BoardDocument = {
  schemaVersion: '1',
  id: 'board:vault:2026-08-23_2026-09-05',
  revision: 'r1',
  metadata: {
    title: 'Vault sprint board',
    purpose: 'Open journal items lifted from the daily notes for triage',
    since: '2026-08-23',
    until: '2026-09-05',
    generatedFrom: 'Daily Notes',
    sourceNotes: [
      'Daily Notes/2026-08-24.md',
      'Daily Notes/2026-08-26.md',
      'Daily Notes/2026-08-29.md',
      'Daily Notes/2026-09-01.md',
      'Daily Notes/2026-09-02.md',
      'Daily Notes/2026-09-04.md',
      'Daily Notes/2026-09-05.md'
    ]
  },
  lanes: [
    {
      id: 'investigate',
      label: 'Investigate'
    },
    {
      id: 'now',
      label: 'Now'
    },
    {
      id: 'next',
      label: 'Next'
    },
    {
      id: 'backlog',
      label: 'Backlog'
    },
    {
      id: 'done',
      label: 'Done'
    }
  ],
  cards: [
    {
      id: 'vt-7c051b3088fe',
      title: 'Verify scene 10697 has a durable backup with checksum/provenance before any source cleanup.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-24 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-24.md',
        sourceLine: 91,
        date: '2026-08-24',
        section: 'TODOs',
        tags: [],
        links: [],
        raw: 'Verify scene 10697 has a durable backup with checksum/provenance before any source cleanup.'
      }
    },
    {
      id: 'vt-0c99008fc845',
      title: 'Verify the manually tagged appears_in relationship is present in the canonical metadata store.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-24 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-24.md',
        sourceLine: 92,
        date: '2026-08-24',
        section: 'TODOs',
        tags: [],
        links: [],
        raw: 'Verify the manually tagged `appears_in` relationship is present in the canonical metadata store.'
      }
    },
    {
      id: 'vt-23c077bead38',
      title: 'Audit police uniform aliases, tag coverage, and related costume/media links; define one searchable canonical concept without deleting existing tags.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-24 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-24.md',
        sourceLine: 93,
        date: '2026-08-24',
        section: 'TODOs',
        tags: [],
        links: [],
        raw: 'Audit `police uniform` aliases, tag coverage, and related costume/media links; define one searchable canonical concept without deleting existing tags.'
      }
    },
    {
      id: 'vt-c760ada7a275',
      title: 'Review scene 4692 and apply verified performer, platform, costume, theme, and series metadata; then confirm it is discoverable through the canonical police uniform concept.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-24 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-24.md',
        sourceLine: 94,
        date: '2026-08-24',
        section: 'TODOs',
        tags: [],
        links: [],
        raw: 'Review scene 4692 and apply verified performer, platform, costume, theme, and series metadata; then confirm it is discoverable through the canonical `police uniform` concept.'
      }
    },
    {
      id: 'vt-465f57c6f3c5',
      title: 'Locate the expected JJ police-uniform video across active Stash records, legacy/test media roots, downloads, and backups; verify the match before tagging or linking it.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-24 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-24.md',
        sourceLine: 95,
        date: '2026-08-24',
        section: 'TODOs',
        tags: [],
        links: [],
        raw: 'Locate the expected JJ police-uniform video across active Stash records, legacy/test media roots, downloads, and backups; verify the match before tagging or linking it.'
      }
    },
    {
      id: 'vt-78f1d25dcac6',
      title: 'Freeze a versioned Shay identity reference set and Stop Traffic costume sheet, including garment parts, materials, colors, footwear, jewelry, props, and negative constraints.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-24 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-24.md',
        sourceLine: 96,
        date: '2026-08-24',
        section: 'TODOs',
        tags: [],
        links: [],
        raw: 'Freeze a versioned Shay identity reference set and Stop Traffic costume sheet, including garment parts, materials, colors, footwear, jewelry, props, and negative constraints.'
      }
    },
    {
      id: 'vt-13f09102f2db',
      title: 'Run a small GPT Image/Create Image consistency matrix: identity-only control, costume-only control, combined full-body front/side/back, and one action pose; preserve prompts, references, outputs, and model settings.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-24 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-24.md',
        sourceLine: 97,
        date: '2026-08-24',
        section: 'TODOs',
        tags: [],
        links: [],
        raw: 'Run a small GPT Image/Create Image consistency matrix: identity-only control, costume-only control, combined full-body front/side/back, and one action pose; preserve prompts, references, outputs, and model settings.'
      }
    },
    {
      id: 'vt-90b54cf34941',
      title: 'Score identity fidelity, costume fidelity, anatomy, prop handling, material consistency, and multi-view coherence before expanding the batch.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-24 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-24.md',
        sourceLine: 98,
        date: '2026-08-24',
        section: 'TODOs',
        tags: [],
        links: [],
        raw: 'Score identity fidelity, costume fidelity, anatomy, prop handling, material consistency, and multi-view coherence before expanding the batch.'
      }
    },
    {
      id: 'vt-fd7c05620df8',
      title: 'If the image test passes, prototype the costume non-destructively in Blender and export a verified glTF/FBX asset for an inZOI or alternative world-sim feasibility test.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-24 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-24.md',
        sourceLine: 99,
        date: '2026-08-24',
        section: 'TODOs',
        tags: [],
        links: [],
        raw: 'If the image test passes, prototype the costume non-destructively in Blender and export a verified glTF/FBX asset for an inZOI or alternative world-sim feasibility test.'
      }
    },
    {
      id: 'vt-feceda6f164f',
      title: 'Capture and classify the 48 focus tabs before closing anything; defer the other 557 tabs rather than processing them tonight.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-24 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-24.md',
        sourceLine: 100,
        date: '2026-08-24',
        section: 'TODOs',
        tags: [],
        links: [],
        raw: 'Capture and classify the 48 focus tabs before closing anything; defer the other 557 tabs rather than processing them tonight.'
      }
    },
    {
      id: 'vt-30307988b102',
      title: 'Review the verified archive summary before deciding whether to delete the corresponding ChatGPT source chats.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-24 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-24.md',
        sourceLine: 102,
        date: '2026-08-24',
        section: 'TODOs',
        tags: [],
        links: [],
        raw: 'Review the verified archive summary before deciding whether to delete the corresponding ChatGPT source chats.'
      }
    },
    {
      id: 'vt-4e8a60e31de8',
      title: 'Review the H3 prompt-composer skill, the MiniMax H3 workflow links, and /home/warby/ComfyUI/output/video/h3_t2v_00001_.mp4; record whether the 3090 workflow is viable.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-26 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-26.md',
        sourceLine: 563,
        date: '2026-08-26',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Review the H3 prompt-composer skill, the MiniMax H3 workflow links, and `/home/warby/ComfyUI/output/video/h3_t2v_00001_.mp4`; record whether the 3090 workflow is viable.'
      }
    },
    {
      id: 'vt-12cfccf7b6d0',
      title: 'Compare Cloudflare Kitesurf/Browser Run with the existing browser-agent architecture and decide whether it merits a vendor review.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-26 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-26.md',
        sourceLine: 564,
        date: '2026-08-26',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Compare Cloudflare Kitesurf/Browser Run with the existing browser-agent architecture and decide whether it merits a vendor review.'
      }
    },
    {
      id: 'vt-7f175c7fa329',
      title: 'Verify the Qwen 3.8 and DeepSeek Harness release/benchmark claims against primary sources before changing the local model stack.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-26 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-26.md',
        sourceLine: 565,
        date: '2026-08-26',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Verify the Qwen 3.8 and DeepSeek Harness release/benchmark claims against primary sources before changing the local model stack.'
      }
    },
    {
      id: 'vt-96677cd31318',
      title: 'Resolve the PostgreSQL/OpenBao secret-storage design using the official pgcrypto and current project policy sources.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-26 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-26.md',
        sourceLine: 566,
        date: '2026-08-26',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Resolve the PostgreSQL/OpenBao secret-storage design using the official pgcrypto and current project policy sources.'
      }
    },
    {
      id: 'vt-e22a6bfd5096',
      title: 'Review the waterfall/game-networking reference stack and select one small world-engine experiment.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-26 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-26.md',
        sourceLine: 567,
        date: '2026-08-26',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Review the waterfall/game-networking reference stack and select one small world-engine experiment.'
      }
    },
    {
      id: 'vt-67cf9389b4e3',
      title: 'Consolidate the Pokémon ROM-hacking and emulator tools into one reproducible workbench path.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-26 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-26.md',
        sourceLine: 568,
        date: '2026-08-26',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Consolidate the Pokémon ROM-hacking and emulator tools into one reproducible workbench path.'
      }
    },
    {
      id: 'vt-83a6e6b0ed85',
      title: 'Review ankle dorsiflexion, uneven-glute, and lymphatic references without treating community health claims as medical advice.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-26 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-26.md',
        sourceLine: 569,
        date: '2026-08-26',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Review ankle dorsiflexion, uneven-glute, and lymphatic references without treating community health claims as medical advice.'
      }
    },
    {
      id: 'vt-465192e1b1fd',
      title: 'Review Cursor spend/pricing and redeem any valid OpenRouter credits before purchasing more tooling.',
      laneId: 'investigate',
      kind: 'task',
      preview: {
        kicker: '2026-08-26 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-26.md',
        sourceLine: 570,
        date: '2026-08-26',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Review Cursor spend/pricing and redeem any valid OpenRouter credits before purchasing more tooling.'
      }
    },
    {
      id: 'vt-0d9bdfab46f3',
      title: 'Review the August 29 honeypotting-AI-agents event and any still-active free-game offer before they expire.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-26 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-26.md',
        sourceLine: 571,
        date: '2026-08-26',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Review the August 29 honeypotting-AI-agents event and any still-active free-game offer before they expire.'
      }
    },
    {
      id: 'vt-e7fac35133b8',
      title: 'Use this note and its routed hubs instead of restoring the closed Firefox session.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-26 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-26.md',
        sourceLine: 572,
        date: '2026-08-26',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Use this note and its routed hubs instead of restoring the closed Firefox session.'
      }
    },
    {
      id: 'vt-a90fb412cf16',
      title: 'Regression-test and repair the Reddit ingestor\'s silent 403 skip/false-green path.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-29 - Durable Follow-Ups',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-29.md',
        sourceLine: 110,
        date: '2026-08-29',
        section: 'Durable Follow-Ups',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Regression-test and repair the Reddit ingestor\'s silent 403 skip/false-green path.'
      }
    },
    {
      id: 'vt-1d733a91168e',
      title: 'Turn pcsx2-style-release-notes metadata into a PR template for the first target repository.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-29 - Durable Follow-Ups',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-29.md',
        sourceLine: 111,
        date: '2026-08-29',
        section: 'Durable Follow-Ups',
        tags: [
          'daily',
          'journal'
        ],
        links: [
          'pcsx2-style-release-notes'
        ],
        raw: 'Turn [[pcsx2-style-release-notes]] metadata into a PR template for the first target repository.'
      }
    },
    {
      id: 'vt-05b574b00a5f',
      title: 'Add followed-artist official-store discovery to Maya\'s music feed.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-29 - Durable Follow-Ups',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-29.md',
        sourceLine: 112,
        date: '2026-08-29',
        section: 'Durable Follow-Ups',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Add followed-artist official-store discovery to Maya\'s music feed.'
      }
    },
    {
      id: 'vt-90c812fb9ac4',
      title: 'Reproduce the pico-faces floating-point fast baseline before QAT.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-29 - Durable Follow-Ups',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-29.md',
        sourceLine: 113,
        date: '2026-08-29',
        section: 'Durable Follow-Ups',
        tags: [
          'daily',
          'journal'
        ],
        links: [
          'tiny-image-generation-on-rp2350'
        ],
        raw: 'Reproduce the [[tiny-image-generation-on-rp2350|pico-faces]] floating-point fast baseline before QAT.'
      }
    },
    {
      id: 'vt-362f2472f278',
      title: 'Apply the sorted-order/RNG and typed-effect fixes from luadb to World’s authoritative core.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-29 - Durable Follow-Ups',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-29.md',
        sourceLine: 114,
        date: '2026-08-29',
        section: 'Durable Follow-Ups',
        tags: [
          'daily',
          'journal'
        ],
        links: [
          'luadb'
        ],
        raw: 'Apply the sorted-order/RNG and typed-effect fixes from [[luadb]] to World’s authoritative core.'
      }
    },
    {
      id: 'vt-cb4d62e2b35c',
      title: 'Review and route the final Reddit deep-crawl exceptions: removed posts, inaccessible galleries, and resources without stable provenance.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-29 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-29.md',
        sourceLine: 118,
        date: '2026-08-29',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Review and route the final Reddit deep-crawl exceptions: removed posts, inaccessible galleries, and resources without stable provenance.'
      }
    },
    {
      id: 'vt-f7a9095fae47',
      title: 'Reopen only the links preserved in 2026-08-29-brain-dump; do not restore the full browser session.',
      laneId: 'backlog',
      kind: 'task',
      preview: {
        kicker: '2026-08-29 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-08-29.md',
        sourceLine: 119,
        date: '2026-08-29',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [
          '2026-08-29-brain-dump'
        ],
        raw: 'Reopen only the links preserved in [[2026-08-29-brain-dump]]; do not restore the full browser session.'
      }
    },
    {
      id: 'vt-f357139867f0',
      title: 'Review and improve the link-based qBittorrent → Plex/Prologue audiobook import workflow.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-01 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-01.md',
        sourceLine: 111,
        date: '2026-09-01',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Review and improve the link-based qBittorrent → Plex/Prologue audiobook import workflow.'
      }
    },
    {
      id: 'vt-6fa5681cae69',
      title: 'Define a versioned chat envelope with event_id, client_message_id, room_sequence, and replay cursor.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-01 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-01.md',
        sourceLine: 112,
        date: '2026-09-01',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Define a versioned chat envelope with `event_id`, `client_message_id`, `room_sequence`, and replay cursor.'
      }
    },
    {
      id: 'vt-26595a3e41bc',
      title: 'Prototype durable append/replay and verify duplicate-send, reconnect, and crash behavior.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-01 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-01.md',
        sourceLine: 113,
        date: '2026-09-01',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Prototype durable append/replay and verify duplicate-send, reconnect, and crash behavior.'
      }
    },
    {
      id: 'vt-b021aa917c73',
      title: 'Write the overload matrix for durable, coalescible, lossy, and rejectable events.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-01 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-01.md',
        sourceLine: 114,
        date: '2026-09-01',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Write the overload matrix for durable, coalescible, lossy, and rejectable events.'
      }
    },
    {
      id: 'vt-e0cae7c4838f',
      title: 'Finish and runtime-verify Kino radio rendering, queue, history, waveform, album art, and volume control.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-02 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-02.md',
        sourceLine: 84,
        date: '2026-09-02',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Finish and runtime-verify Kino radio rendering, queue, history, waveform, album art, and volume control.'
      }
    },
    {
      id: 'vt-8fbae06ea69e',
      title: 'Verify MissKatie cron jobs no longer deliver to Discord while continuing to run.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-02 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-02.md',
        sourceLine: 85,
        date: '2026-09-02',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Verify MissKatie cron jobs no longer deliver to Discord while continuing to run.'
      }
    },
    {
      id: 'vt-f24d4022a919',
      title: 'Set up Omega Ruby from owned content and document reproducibility/hash evidence in the existing 3DS/ROM wiki.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-02 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-02.md',
        sourceLine: 86,
        date: '2026-09-02',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Set up Omega Ruby from owned content and document reproducibility/hash evidence in the existing 3DS/ROM wiki.'
      }
    },
    {
      id: 'vt-a3d481529316',
      title: 'Audit the booru tables and mark the required schema/table work.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-04 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-04.md',
        sourceLine: 66,
        date: '2026-09-04',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Audit the booru tables and mark the required schema/table work.'
      }
    },
    {
      id: 'vt-910c5cb1b978',
      title: 'Ingest the three captured Reddit posts into the booru with source provenance.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-04 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-04.md',
        sourceLine: 67,
        date: '2026-09-04',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Ingest the three captured Reddit posts into the booru with source provenance.'
      }
    },
    {
      id: 'vt-ffe08a62eb8b',
      title: 'Configure frequent subreddit collection runs using our collection bias.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-04 - TODOs',
        metrics: []
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-04.md',
        sourceLine: 68,
        date: '2026-09-04',
        section: 'TODOs',
        tags: [
          'daily',
          'journal'
        ],
        links: [],
        raw: 'Configure frequent subreddit collection runs using our collection bias.'
      }
    },
    {
      id: 'vt-cb2ba921e10e',
      title: 'Urgent: investigate the unauthorized OpenRouter API-key-use alert, revoke/rotate the affected key, review provider usage, and invalidate exposed sessions without copying credentials into the vault.',
      laneId: 'investigate',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 158,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Urgent: investigate the unauthorized OpenRouter API-key-use alert, revoke/rotate the affected key, review provider usage, and invalidate exposed sessions without copying credentials into the vault.'
      }
    },
    {
      id: 'vt-648ea196b60c',
      title: 'Create a path-scoped sprint manifest for the relevant changes in /home/warby/Workspace-end and /home/warby/Workspace-git/maya-unified; do not alter unrelated dirty work.',
      laneId: 'now',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 159,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Create a path-scoped sprint manifest for the relevant changes in `/home/warby/Workspace-end` and `/home/warby/Workspace-git/maya-unified`; do not alter unrelated dirty work.'
      }
    },
    {
      id: 'vt-f0b5c73581e0',
      title: 'Classify and hash-map the downloaded artifacts as adopt/adapt/reference-only/duplicate, then move no files until the mapping is reviewed.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 160,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Classify and hash-map the downloaded artifacts as adopt/adapt/reference-only/duplicate, then move no files until the mapping is reviewed.'
      }
    },
    {
      id: 'vt-62b9f94a92b7',
      title: 'Define the canonical workspace/layout_pokeforce Lua DSL as a projection onto the existing typed Endgame DAG, not a parallel runtime.',
      laneId: 'now',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 161,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Define the canonical `workspace/layout_pokeforce` Lua DSL as a projection onto the existing typed Endgame DAG, not a parallel runtime.'
      }
    },
    {
      id: 'vt-7314fa82d14d',
      title: 'Port the deterministic humanized A* policy into Rust with legality, excess-cost, seed-replay, and synthetic-provenance tests.',
      laneId: 'now',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 162,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Port the deterministic humanized A* policy into Rust with legality, excess-cost, seed-replay, and synthetic-provenance tests.'
      }
    },
    {
      id: 'vt-22b3805192e4',
      title: 'Implement the live logical-state adapter and acknowledged adjacent-step executor; eliminate timing-only movement from the production path.',
      laneId: 'now',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 163,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Implement the live logical-state adapter and acknowledged adjacent-step executor; eliminate timing-only movement from the production path.'
      }
    },
    {
      id: 'vt-1f475d94b26b',
      title: 'Add live player marker, observed trail, planned route, first-divergence marker, and evidence references to the radar/World view.',
      laneId: 'now',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 164,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Add live player marker, observed trail, planned route, first-divergence marker, and evidence references to the radar/World view.'
      }
    },
    {
      id: 'vt-1281df58f7df',
      title: 'Complete and record the remaining tutorial phases on one account, then replay on Vivi/Maya/Lain as isolated validation runs.',
      laneId: 'now',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 165,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Complete and record the remaining tutorial phases on one account, then replay on Vivi/Maya/Lain as isolated validation runs.'
      }
    },
    {
      id: 'vt-b37f48a9418d',
      title: 'Establish focused green verification commands for the PokéForce slice before any checkpoint/commit decision.',
      laneId: 'now',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 166,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Establish focused green verification commands for the PokéForce slice before any checkpoint/commit decision.'
      }
    },
    {
      id: 'vt-745aef31c561',
      title: 'Convert the open Stash/booru/source tabs into canonical source records with stable IDs, provenance, deduplication, and review state; use the tab inventory as the bounded queue.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 167,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Convert the open Stash/booru/source tabs into canonical source records with stable IDs, provenance, deduplication, and review state; use the tab inventory as the bounded queue.'
      }
    },
    {
      id: 'vt-522e87dcabde',
      title: 'Evaluate the agent-training/environment-simulation references against the existing replay contract: state authority, action acknowledgement, uncertainty, and synthetic-evidence labeling.',
      laneId: 'now',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 168,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Evaluate the agent-training/environment-simulation references against the existing replay contract: state authority, action acknowledgement, uncertainty, and synthetic-evidence labeling.'
      }
    },
    {
      id: 'vt-a0da20934ca7',
      title: 'Review the captured media-broker tabs as one request lifecycle and verify Query Broker → download client → library availability before closing the operational queue.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 169,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Review the captured media-broker tabs as one request lifecycle and verify Query Broker → download client → library availability before closing the operational queue.'
      }
    },
    {
      id: 'vt-dadfca86c2d2',
      title: 'After reviewing both inventories, explicitly approve closing the captured Firefox and Helium tabs; this ritual captured them but did not alter browser state.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 170,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'After reviewing both inventories, explicitly approve closing the captured Firefox and Helium tabs; this ritual captured them but did not alter browser state.'
      }
    },
    {
      id: 'vt-70b52fa58d4f',
      title: 'Reopen Files and visually verify WebM thumbnails repopulate, then run the normal NixOS activation and remove the temporary profile package if redundant.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 171,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Reopen Files and visually verify WebM thumbnails repopulate, then run the normal NixOS activation and remove the temporary profile package if redundant.'
      }
    },
    {
      id: 'vt-7582f6eed9a4',
      title: 'Record a Toy Story query-broker acceptance matrix covering sequel numbering, the unreleased fifth film, and movie-versus-TV-special resolution.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 172,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Record a Toy Story query-broker acceptance matrix covering sequel numbering, the unreleased fifth film, and movie-versus-TV-special resolution.'
      }
    },
    {
      id: 'vt-d9c8c3cf73ce',
      title: 'Compare the inspected RealityKings/Data18 CommunityScrapers with current Stash metadata gaps using one reproducible scene and explicit missing fields before changing a scraper.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 173,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Compare the inspected RealityKings/Data18 CommunityScrapers with current Stash metadata gaps using one reproducible scene and explicit missing fields before changing a scraper.'
      }
    },
    {
      id: 'vt-2b74ddae734a',
      title: 'Review Traefik header-alias spoofing mitigation against the current proxy configuration and trust boundary.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 174,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Review Traefik header-alias spoofing mitigation against the current proxy configuration and trust boundary.'
      }
    },
    {
      id: 'vt-3c3bdb94f4bf',
      title: 'Verify the 2026-09-04/05 ChatGPT archive runs and build a hash-locked Shay/Nicole candidate manifest; annotations remain suggestions and training export stays blocked pending review and policy approval.',
      laneId: 'next',
      kind: 'task',
      preview: {
        kicker: '2026-09-05 - TODOs',
        metrics: [
          'pokeforce',
          'automation',
          'lua',
          'rust'
        ]
      },
      payload: {
        sourceNote: 'Daily Notes/2026-09-05.md',
        sourceLine: 175,
        date: '2026-09-05',
        section: 'TODOs',
        tags: [
          'daily',
          'journal',
          'pokeforce',
          'automation',
          'lua',
          'rust',
          'pathfinding'
        ],
        links: [],
        raw: 'Verify the 2026-09-04/05 ChatGPT archive runs and build a hash-locked Shay/Nicole candidate manifest; annotations remain suggestions and training export stays blocked pending review and policy approval.'
      }
    }
  ]
}
