import { expect, test } from '@playwright/test'

test('Svelte docs render live component pages and route search', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')

  await expect(page.getByRole('heading', { name: 'Tint components' })).toBeVisible()
  await page.getByRole('link', { name: 'Button Actions with Tint variants, sizes, and loading state.' }).click()
  await expect(page.getByRole('heading', { name: 'Button', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Primary' }).click()
  await expect(page.getByText('Activations: 1')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'API' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Accessibility' })).toBeVisible()

  await page.getByRole('searchbox', { name: 'Search components' }).fill('progress')
  await expect(page.getByRole('navigation', { name: 'Component documentation' }).getByRole('link', { name: 'Progress' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Component documentation' }).getByRole('link', { name: 'Panel' })).toHaveCount(0)
  await page.getByRole('navigation', { name: 'Component documentation' }).getByRole('link', { name: 'Progress' }).click()
  await expect(page.getByRole('heading', { name: 'Progress', exact: true })).toBeVisible()
  await expect(page.getByRole('progressbar', { name: 'Example transfer' })).toHaveAttribute('aria-valuenow', '64')
  await page.getByRole('slider', { name: 'Progress: 64%' }).fill('80')
  await expect(page.getByRole('progressbar', { name: 'Example transfer' })).toHaveAttribute('aria-valuenow', '80')

  await page.getByLabel('Theme').selectOption('mocha')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'mocha')
  await page.locator('.topbar').getByRole('radio', { name: 'Light' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-scheme', 'light')
  expect(errors).toEqual([])
})

test('old docs entry and retired hash routes open the Svelte docs', async ({ page }) => {
  await page.goto('/svelte-docs.html#/components/music-library')
  await expect(page).toHaveURL(/\/#\/components\/music-library$/)
  await expect(page.getByRole('heading', { name: 'Table and Workbench' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Component documentation' }).getByRole('link', { name: 'Table and Workbench' })).toHaveAttribute('aria-current', 'page')
})

test('Character Documents docs exercise library search and original document editing', async ({ page }) => {
  await page.goto('/#/components/character-documents')
  await expect(page.getByRole('heading', { name: 'Character Documents' })).toBeVisible()
  const library = page.getByRole('region', { name: 'Character library' })
  await library.getByRole('searchbox', { name: 'Search characters' }).fill('sea')
  await expect(library.getByRole('status')).toHaveText('1 character')
  await library.getByRole('button', { name: 'Chat with Marin' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Start chat with Marin' })).toBeVisible()
  await library.getByRole('button', { name: 'Edit Marin' }).click()
  await expect(page.getByRole('textbox', { name: 'Name' })).toHaveValue('Marin')
  await page.getByRole('textbox', { name: 'Name' }).fill('Marin II')
  await page.getByRole('button', { name: 'Save character' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Saved Marin II in memory.' })).toBeVisible()
})

test('Table docs exercise controlled event review filters, candidates, and media seek', async ({ page }) => {
  await page.goto('/#/components/table')
  const review = page.getByRole('region', { name: 'Event review controls' })
  await review.getByRole('button', { name: 'Flagged' }).click()
  await expect(review.getByRole('button', { name: 'Flagged' })).toHaveAttribute('aria-pressed', 'true')
  await review.getByRole('checkbox', { name: 'Maya' }).check()
  await review.getByRole('button', { name: 'Seek to 1:33' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Filter: flagged; candidates: 1; Seeked to 93s' })).toBeVisible()
  await expect(review.getByText('Training not approved.')).toBeVisible()
})

test('Theme docs share and persist palette and scheme controls with the header', async ({ page }) => {
  await page.goto('/#/components/theme')
  const preview = page.locator('.theme-demo')
  await preview.getByRole('combobox', { name: 'Preview theme' }).selectOption('gruvbox')
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'gruvbox')
  await expect(page.locator('.topbar').getByRole('combobox', { name: 'Theme' })).toHaveValue('gruvbox')
  await preview.getByRole('radio', { name: 'Dark' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-scheme', 'dark')
  await expect(page.locator('.topbar').getByRole('radio', { name: 'Dark' })).toHaveAttribute('aria-checked', 'true')
  await page.reload()
  await expect(preview.getByRole('combobox', { name: 'Preview theme' })).toHaveValue('gruvbox')
  await expect(preview.getByRole('radio', { name: 'Dark' })).toHaveAttribute('aria-checked', 'true')
  await preview.getByRole('radio', { name: 'System' }).click()
  await expect(page.locator('html')).not.toHaveAttribute('data-scheme', /.+/)
  expect(await page.evaluate(() => localStorage.getItem('tint-color-scheme'))).toBeNull()
  await preview.getByRole('combobox', { name: 'Preview theme' }).selectOption('tint')
  await expect(page.locator('html')).not.toHaveAttribute('data-theme', /.+/)
})

test('Svelte docs navigation stays available at mobile width', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/components/panel')
  await expect(page.getByRole('heading', { name: 'Panel', exact: true })).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Component documentation' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Toggle documentation navigation' }).click()
  await expect(page.getByRole('navigation', { name: 'Component documentation' })).toBeInViewport()
  await page.getByRole('button', { name: 'Inspector' }).click()
  await expect(page.getByRole('button', { name: 'Inspector' })).toHaveAttribute('aria-expanded', 'false')
  await page.getByRole('navigation', { name: 'Component documentation' }).getByRole('link', { name: 'Button', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Button', exact: true })).toBeFocused()
  await expect(page.getByRole('navigation', { name: 'Component documentation' })).toHaveCount(0)
})

test('Svelte interaction docs exercise controlled menu, tabs, dialog, and context menu', async ({ page }) => {
  await page.goto('/#/components/menu')
  await page.getByRole('button', { name: 'Actions', exact: true }).click()
  await expect(page.getByRole('menu', { name: 'Actions' })).toBeVisible()
  await page.getByRole('menuitem', { name: 'Share' }).click()
  await expect(page.getByText('Selected: Share')).toBeVisible()

  await page.goto('/#/components/tabs')
  await page.getByRole('tab', { name: 'History' }).click()
  await expect(page.getByRole('tabpanel', { name: 'History' })).toHaveText('Recent changes to the collection.')

  await page.goto('/#/components/dialog')
  await page.getByRole('button', { name: 'Open dialog' }).click()
  await expect(page.getByRole('dialog', { name: 'Create view' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Create view' })).not.toBeVisible()

  await page.goto('/#/components/context-menu')
  await page.getByRole('button', { name: 'Open actions with keyboard or touch' }).click()
  await expect(page.getByRole('menu', { name: 'Context menu' })).toBeVisible()
  await page.getByRole('menuitem', { name: 'Copy link' }).click()
  await expect(page.getByText('Selected: Copy link')).toBeVisible()

  await page.goto('/#/components/toast')
  await page.getByRole('button', { name: 'Show success' }).click()
  await expect(page.getByText('Collection saved')).toBeVisible()
  await page.getByRole('button', { name: 'Dismiss' }).click()
  await expect(page.getByText('Collection saved')).not.toBeVisible()
})

test('Dice settles on the host result without animation under reduced motion', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/#/components/dice')
  await page.getByRole('button', { name: 'Roll', exact: true }).click()
  await expect(page.getByRole('status', { name: 'Rolling' })).toHaveCSS('animation-name', 'none')
  await expect(page.getByRole('status')).toHaveAttribute('aria-label', /^Rolled \d+$/)
})

test('Table docs keep sorting, selection, and inspector state controlled', async ({ page }) => {
  await page.goto('/#/components/table')
  const table = page.getByRole('table', { name: 'Demo tracks' })
  await expect(table).toBeVisible()
  await table.getByRole('button', { name: 'Sort by Track' }).click()
  await expect(table.getByRole('columnheader', { name: /Track/ })).toHaveAttribute('aria-sort', 'ascending')
  await table.getByRole('checkbox', { name: 'Select Night Drive' }).check()
  await expect(page.getByText('Selected IDs: a')).toBeVisible()

  const workbench = page.locator('[data-collection-workbench]')
  await expect(workbench.getByRole('table', { name: 'Track collection' })).toBeVisible()
  await workbench.getByRole('button', { name: 'Open Night Drive' }).click()
  await workbench.getByRole('tab', { name: 'History' }).click()
  await expect(workbench.getByRole('tabpanel', { name: 'History' })).toContainText('Change history for Night Drive.')
})

test('Auth docs exercise the pure client through Svelte forms', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/#/components/auth')
  await expect(page.getByRole('heading', { name: 'Auth', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByText('Signed in as operator')).toBeVisible()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByRole('textbox', { name: 'Email or username' }).fill('mfa@example.test')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByLabel(/Six-digit code/)).toBeVisible()
  await page.getByLabel(/Six-digit code/).fill('123456')
  await page.getByRole('button', { name: 'Verify code' }).click()
  await expect(page.getByText('Signed in as mfa')).toBeVisible()
  expect(errors).toEqual([])
})

test('Character Card docs import a card and export the controlled value', async ({ page }) => {
  await page.goto('/#/components/character-card')
  await expect(page.getByRole('heading', { name: 'Character Card', exact: true })).toBeVisible()
  await page.getByLabel('Choose character JSON').setInputFiles({
    name: 'test-character.json',
    mimeType: 'application/json',
    buffer: Buffer.from(JSON.stringify({ spec: 'chara_card_v2', data: { name: 'Mira', extensions: { custom: 'preserved' } } })),
  })
  await expect(page.locator('p[role="status"]')).toHaveText('Imported test-character.json')
  await expect(page.getByRole('textbox', { name: 'Name *', exact: true })).toHaveValue('Mira')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export JSON' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('Mira.json')
})

test('Code docs preserve text and navigate tabs by keyboard', async ({ page }) => {
  await page.goto('/#/components/code')
  await expect(page.getByRole('heading', { name: 'Code', exact: true })).toBeVisible()
  const tabs = page.getByRole('tablist', { name: 'Code examples' })
  await tabs.getByRole('tab', { name: 'TypeScript' }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(tabs.getByRole('tab', { name: 'Python' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('tabpanel')).toContainText('print(greeting)')
  await expect(page.getByText('Active language: python')).toBeVisible()
  await expect(page.locator('.code-demo > div pre code')).toContainText('<div class="x">{a && b}</div>')
})

test('Calendar docs keep month, day, and event intent host controlled', async ({ page }) => {
  await page.goto('/#/components/calendar')
  const calendar = page.getByRole('grid', { name: 'Demo calendar' })
  await expect(calendar).toBeVisible()
  await calendar.getByRole('gridcell', { name: '2026-09-24' }).click()
  await expect(page.getByText(/Selected day: 2026-09-24/)).toBeVisible()
  await calendar.getByRole('button', { name: 'Design review' }).click()
  await expect(page.getByText(/Event: Design review/)).toBeVisible()
  await page.getByRole('button', { name: 'Next month' }).click()
  await expect(page.getByRole('heading', { name: 'October 2026' })).toBeVisible()
})

test('Navigation docs show the responsive controlled drawer', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/#/components/navigation')
  const shell = page.locator('[data-tint-app-shell]')
  await expect(shell).toHaveAttribute('data-sidebar-presentation', 'overlay')
  await shell.getByRole('button', { name: 'Open Navigation' }).click()
  await expect(shell.getByRole('dialog', { name: 'Navigation' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(shell.getByRole('dialog', { name: 'Navigation' })).toHaveCount(0)
  await expect(shell.getByRole('button', { name: 'Open Navigation' })).toBeFocused()
})

test('Shell docs keep tabs, split size, and command selection controlled', async ({ page }) => {
  await page.goto('/#/components/shell')
  await page.getByRole('tab', { name: 'History' }).click()
  await expect(page.getByText('Recent activity')).toBeVisible()
  const separator = page.getByRole('separator', { name: 'Resize inspector' })
  await separator.focus()
  await page.keyboard.press('ArrowRight')
  await expect(separator).toHaveAttribute('aria-valuenow', '240')
  await page.getByRole('button', { name: 'Open command palette' }).click()
  await page.getByRole('combobox', { name: 'Command palette' }).fill('share')
  await page.keyboard.press('Enter')
  await expect(page.getByText('Selected command: share')).toBeVisible()
  await expect(page.getByRole('dialog', { name: 'Command palette' })).toHaveCount(0)
})

test('Board docs keep layout and selection controlled', async ({ page }) => {
  await page.goto('/#/components/board')
  await page.getByRole('button', { name: 'Relationship map' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByText('Layout: masonry · Selected: Relationship map')).toBeVisible()
  await page.getByRole('button', { name: 'Kanban' }).click()
  await expect(page.locator('[data-tint-board-layout]')).toHaveAttribute('data-variant', 'kanban')
  await expect(page.getByRole('region', { name: 'In progress' })).toContainText('Night Drive mix')
})

test('Media docs switch player kinds and keep queue and settings controlled', async ({ page }) => {
  await page.goto('/#/components/media')
  await expect(page.locator('[data-tint-media-player]')).toHaveAttribute('data-kind', 'audio')
  await page.getByRole('group', { name: 'Media kind' }).getByRole('button', { name: 'Video' }).click()
  await expect(page.locator('[data-tint-video-player]')).toBeVisible()
  await page.getByRole('group', { name: 'Media kind' }).getByRole('button', { name: 'Audio' }).click()
  await page.locator('[data-tint-playback-queue] button').nth(1).click()
  await expect(page.getByRole('button', { name: 'Play Night Drive' })).toBeVisible()
  await page.getByRole('button', { name: 'Playback settings' }).click()
  await page.getByRole('option', { name: 'Fast' }).click()
  await expect(page.getByText('Speed: fast')).toBeVisible()
})

test('Terminal docs preserve the host session through disconnect and reconnect', async ({ page }) => {
  await page.goto('/#/components/terminal')
  await expect(page.getByRole('application', { name: 'Demo terminal viewport' })).toBeVisible()
  await page.getByRole('button', { name: 'Disconnect' }).click()
  await expect(page.getByText('Disconnected', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Reconnect terminal' }).click()
  await expect(page.getByText('Connected', { exact: true })).toBeVisible()
})

test('Code Editor docs mount the shared session and toggle read only', async ({ page }) => {
  await page.goto('/#/components/code-editor')
  const editor = page.locator('[data-tint-code-editor] .cm-content')
  await expect(editor).toBeVisible()
  await expect(editor).toContainText('Hello, Tint')
  await page.getByRole('checkbox', { name: 'Read only' }).check()
  await expect(editor).toHaveAttribute('aria-readonly', 'true')
  await editor.click()
  await page.keyboard.type('X')
  await expect(editor).not.toContainText('X')
})

test('Editor docs keep JSON, disclosure, and read-only state with the host', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/#/components/editor')
  await expect(page.getByRole('heading', { name: 'Editor', exact: true })).toBeVisible()
  const editor = page.getByRole('textbox', { name: 'Demo article body' })
  await expect(editor).toContainText('Draft release note')
  await editor.locator('p').click()
  await page.keyboard.press('End')
  await page.keyboard.type(' Added in browser.')
  await expect(editor).toContainText('Added in browser.')
  await expect(page.locator('.editor-demo .summary')).toContainText(/Edits: [1-9]/)

  const editsBeforeReplace = await page.locator('.editor-demo .summary').textContent()
  await page.getByRole('button', { name: 'Replace document' }).click()
  await expect(editor).toContainText('Host replacement document')
  expect(await page.locator('.editor-demo .summary').textContent()).toBe(editsBeforeReplace)

  await page.getByRole('button', { name: 'Release note' }).click()
  await expect(page.locator('.editor-demo .summary')).toContainText('Expanded: no')
  await page.getByRole('button', { name: 'Release note' }).click()
  await expect(editor).toBeVisible()
  await page.getByRole('checkbox', { name: 'Read only' }).check()
  await expect(editor).toHaveAttribute('contenteditable', 'false')
  await expect(page.getByRole('toolbar', { name: 'Document formatting' })).toHaveCount(0)
  await page.getByRole('checkbox', { name: 'Read only' }).uncheck()
  await page.getByRole('button', { name: 'Insert tabbed code' }).click()
  await expect(page.locator('[data-tint-code-tabs-node]')).toBeVisible()
  expect(errors).toEqual([])
})

test('Media Assets docs open the controlled lightbox and validate files', async ({ page }) => {
  await page.goto('/#/components/media-assets')
  await page.getByRole('button', { name: 'View Abstract teal circles' }).click()
  await expect(page.getByRole('dialog', { name: 'Teal circles' })).toBeVisible()
  await page.getByRole('button', { name: 'Next' }).click()
  await expect(page.getByRole('dialog', { name: 'Orange shapes' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.locator('[data-tint-upload-dropzone] input[type="file"]').setInputFiles({
    name: 'notes.txt', mimeType: 'text/plain', buffer: Buffer.from('not an image'),
  })
  await expect(page.getByRole('status')).toContainText('not an accepted file type')
})

test('Chart docs keep point selection accessible through the data table', async ({ page }) => {
  await page.goto('/#/components/release-chart')
  await expect(page.getByRole('img', { name: 'Release scores compared with file size' })).toBeVisible()
  await page.getByRole('table', { name: 'Demo release data' }).getByRole('button', { name: 'Midnight' }).click()
  await expect(page.getByText('Selected release: Midnight')).toBeVisible()
})

test('Voice Input docs keep draft and availability controlled', async ({ page }) => {
  await page.goto('/#/components/audio-input')
  await page.getByRole('textbox', { name: 'Draft' }).fill('Existing words')
  await expect(page.getByRole('button', { name: 'Start Voice draft' })).toBeEnabled()
  await page.getByRole('checkbox', { name: 'Disable voice input' }).check()
  await expect(page.getByRole('button', { name: 'Start Voice draft' })).toBeDisabled()
  await expect(page.getByRole('textbox', { name: 'Draft' })).toHaveValue('Existing words')
})

test('Framebuffer docs discover sessions and keep selection keyboard accessible', async ({ page }) => {
  await page.route('**/api/workbench/list_sessions', async (route) => {
    await route.fulfill({ contentType: 'application/json', body: JSON.stringify({ sessions: [
      { account_id: 'alpha' }, { account_id: 'beta' },
    ] }) })
  })
  await page.goto('/#/components/framebuffer')
  const tabs = page.getByRole('tablist', { name: 'Game clients' })
  await expect(tabs.getByRole('tab', { name: 'alpha' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('img', { name: 'alpha native framebuffer' })).toBeVisible()
  await tabs.getByRole('tab', { name: 'beta' }).click()
  await expect(page.getByRole('img', { name: 'beta native framebuffer' })).toBeVisible()
  await page.keyboard.press('ArrowLeft')
  await expect(tabs.getByRole('tab', { name: 'alpha' })).toHaveAttribute('aria-selected', 'true')
  await expect(tabs.getByRole('tab', { name: 'alpha' })).toBeFocused()
})

test('Charts docs expose both visual plots and exact values', async ({ page }) => {
  await page.goto('/#/components/charts')
  await expect(page.getByRole('img', { name: 'Weekly plays and saves' })).toBeVisible()
  await expect(page.getByRole('img', { name: 'Daily plays and saves' })).toBeVisible()
  await page.getByText('View data table').first().click()
  await expect(page.getByRole('table', { name: 'Weekly listening data' })).toContainText('Fri')
  await expect(page.getByRole('table', { name: 'Weekly listening data' })).toContainText('64')
})

test('Telemetry docs keep span and service selection controlled', async ({ page }) => {
  await page.goto('/#/components/telemetry')
  await page.getByRole('option', { name: /response\.generate/ }).click()
  await expect(page.getByText('Selected span: generate · Service: none')).toBeVisible()
  await page.locator('[data-trace-service-map]').getByRole('button', { name: /model: 1 span/ }).click()
  await expect(page.getByText('Selected span: generate · Service: model')).toBeVisible()
  await expect(page.getByText('Failed spans present')).toBeVisible()
})

test('Feed docs switch layouts and show the selected article', async ({ page }) => {
  await page.goto('/#/components/feed')
  await page.getByRole('group', { name: 'Feed layout' }).getByRole('button', { name: 'List' }).click()
  await expect(page.locator('[data-tint-feed-layout]')).toHaveAttribute('data-variant', 'list')
  await page.getByRole('button', { name: 'Production notes from the forum' }).focus()
  await page.keyboard.press('Space')
  await expect(page.locator('[data-tint-reader-pane]')).toContainText('Forum members suggested a shorter intro')
  await expect(page.getByText('Selected entry: Production notes from the forum')).toBeVisible()
})

test('Activity docs keep sort and row selection controlled', async ({ page }) => {
  await page.goto('/#/components/activity')
  await page.getByRole('group', { name: 'Activity sort' }).getByRole('button', { name: 'top' }).click()
  await expect(page.getByText('Sort: top · Selected: none')).toBeVisible()
  await page.getByRole('button', { name: 'Select Forum arrangement notes' }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByText('Sort: top · Selected: forum')).toBeVisible()
})

test('Notification docs keep read state and delivery settings controlled', async ({ page }) => {
  await page.goto('/#/components/notify')
  await expect(page.getByText('Unread: 2')).toBeVisible()
  await page.getByRole('button', { name: 'Notifications, 2 unread' }).click()
  await expect(page.getByRole('dialog', { name: 'Notifications' })).toBeVisible()
  await page.getByRole('button', { name: 'Night Drive mix is ready' }).click()
  await expect(page.getByText('Unread: 1')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('combobox', { name: 'Default' }).selectOption('digest')
  await expect(page.getByText('Default delivery: digest')).toBeVisible()
})

test('Tile Map docs forward keyboard intent to the host client', async ({ page }) => {
  await page.route('**/pokeforce/map.json', async (route) => route.fulfill({ status: 404 }))
  await page.goto('/#/components/tile-map')
  const map = page.getByRole('button', { name: 'Game map' })
  await expect(map).toBeVisible()
  await expect(page.getByText('Position (12, 8)')).toBeVisible()
  await map.focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByText('Position (13, 8)')).toBeVisible()
  await expect(page.getByRole('status')).toContainText('MoveIntent accepted · right')
  await page.keyboard.press('e')
  await expect(page.getByRole('status')).toContainText('InteractIntent')
})

test('Annotation docs emit box and polygon intents to the host', async ({ page }) => {
  await page.goto('/#/components/annotation')
  const editor = page.getByRole('application', { name: /Annotation editor/ })
  await page.getByRole('group', { name: 'Annotation tool' }).getByRole('button', { name: 'box' }).click()
  const bounds = await editor.boundingBox()
  expect(bounds).not.toBeNull()
  const x = bounds!.x
  const y = bounds!.y
  await page.mouse.move(x + 30, y + 30)
  await page.mouse.down()
  await page.mouse.move(x + 130, y + 110)
  await page.mouse.up()
  await expect(page.getByText('Tool: select · Regions: 2 · Selected: region-1')).toBeVisible()
  await page.getByRole('group', { name: 'Annotation tool' }).getByRole('button', { name: 'polygon' }).click()
  await page.mouse.click(x + 180, y + 40)
  await page.mouse.click(x + 250, y + 40)
  await page.mouse.click(x + 220, y + 100)
  await editor.press('Enter')
  await expect(page.getByText('Tool: select · Regions: 3 · Selected: region-2')).toBeVisible()
  await editor.press('Delete')
  await expect(page.getByText('Tool: select · Regions: 2 · Selected: none')).toBeVisible()
})

test('Policy docs edit host-owned rules and show workflow without running Lua', async ({ page }) => {
  await page.goto('/#/components/policy')
  await expect(page.getByRole('table', { name: 'Policy rules' })).toBeVisible()
  await expect(page.locator('[data-tint-graph-view]')).toBeVisible()
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Updated lab uploads')
  await page.getByRole('button', { name: 'Save rule' }).click()
  await expect(page.getByRole('table', { name: 'Policy rules' })).toContainText('Updated lab uploads')
  await page.getByRole('group', { name: 'Criteria mode' }).getByRole('button', { name: 'Lua' }).click()
  await page.getByRole('textbox', { name: 'Lua source' }).fill('return true')
  await expect(page.getByLabel('Lua preview')).toContainText('return true')
  await page.getByRole('button', { name: 'Run dry-run' }).click()
  await expect(page.locator('[data-tint-policy-dry-run]')).toContainText('mock')
})

test('Identity docs show named avatars, presence, and overflow', async ({ page }) => {
  await page.goto('/#/components/identity')
  await expect(page.getByLabel('Mira Patel').first()).toBeVisible()
  await expect(page.locator('[data-tint-avatar-group]')).toContainText('+2')
  await expect(page.locator('[data-avatar-presence][data-presence="online"]').first()).toBeVisible()
  await expect(page.getByLabel('Taylor Doe')).toBeVisible()
})

test('Graph docs keep document, selection, and timeline edits with the host', async ({ page }) => {
  await page.goto('/#/components/graph')
  const graph = page.locator('[data-tint-graph-view]')
  const trigger = graph.getByRole('button', { name: /Webhook received \(trigger, ready\)/ })
  await trigger.click()
  await expect(page.getByText('Selected nodes: 1 · Last command: selection.replace')).toBeVisible()
  await trigger.focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByText('Selected nodes: 1 · Last command: node.move')).toBeVisible()
  await graph.getByRole('button', { name: 'Zoom in' }).click()
  await expect(page.getByText('Selected nodes: 1 · Last command: viewport.set')).toBeVisible()
  await page.getByLabel('Layout').selectOption('range')
  const start = page.getByRole('slider', { name: 'Webhook received start' })
  await expect(start).toBeVisible()
  await start.focus()
  await page.keyboard.press('ArrowRight')
  await expect(start).toHaveAttribute('aria-valuenow', '2.36')
  await expect(page.getByRole('group', { name: /Network view/ })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(graph).toHaveAttribute('data-compact', 'true')
})

test('DJ docs keep presets, audition state, and retry intent with the host', async ({ page }) => {
  await page.goto('/#/components/dj')
  await expect(page.locator('[data-tint-dual-waveform]')).toBeVisible()
  await page.getByRole('radio', { name: 'Filter and echo exit' }).check()
  await expect(page.getByText('Preview state: idle · Preset: filter-echo-exit')).toBeVisible()
  await page.getByRole('button', { name: 'Audition transition' }).click()
  await expect(page.getByText('Preview state: playing · Preset: filter-echo-exit')).toBeVisible()
  await page.getByRole('button', { name: 'Stop audition' }).click()
  await page.getByRole('button', { name: 'Retry Afterglow.wav' }).click()
  await expect(page.getByRole('region', { name: 'Track analysis queue' }).getByRole('status')).toContainText('2 of 2 tracks ready')
})

test('Midnight 128 docs keep local import controlled and expose engine state', async ({ page }) => {
  await page.goto('/#/components/midnight-128')
  await expect(page.getByRole('dialog', { name: 'Import local tracks' })).toBeVisible()
  await expect(page.getByText(/Web Audio: (available|unavailable)/)).toBeVisible()
  await page.getByRole('button', { name: 'Cancel import' }).click()
  await expect(page.getByRole('dialog', { name: 'Import local tracks' })).toBeHidden()
  await page.getByRole('button', { name: 'Import reference tracks' }).click()
  await expect(page.getByRole('dialog', { name: 'Import local tracks' })).toBeVisible()
})

test('Client docs bind plain TypeScript playback and operations to Svelte snapshots', async ({ page }) => {
  await page.goto('/#/components/client')
  await expect(page.getByRole('status')).toContainText('Client: ready')
  await expect(page.getByText('Current track: Night Drive · paused')).toBeVisible()
  await page.getByRole('button', { name: 'Toggle playback' }).click()
  await expect(page.getByText('Current track: Night Drive · playing')).toBeVisible()
  await page.getByRole('button', { name: 'Submit operation' }).click()
  await expect(page.getByRole('list', { name: 'Operations' })).toContainText('demo:refresh: succeeded')
  await page.getByRole('button', { name: 'Clear settled' }).click()
  await expect(page.getByRole('list', { name: 'Operations' })).toContainText('No operations yet')
})

test('Collaboration docs sync independent Yjs sessions in the same room', async ({ page }) => {
  await page.goto('/#/components/collab')
  await page.getByRole('textbox', { name: 'Editor A' }).fill('Shared note')
  await expect(page.getByRole('textbox', { name: 'Editor B' })).toHaveValue('Shared note')
  await page.getByRole('textbox', { name: 'Editor B' }).fill('Updated by B')
  await expect(page.getByRole('textbox', { name: 'Editor A' })).toHaveValue('Updated by B')
})

test('Dependency Graph docs navigate from a generated package node', async ({ page }) => {
  await page.goto('/#/components/dependency-graph')
  await expect(page.getByText(/generated component import graph contains/)).toBeVisible()
  await page.getByRole('button', { name: /graph \(action,/ }).click()
  await expect(page).toHaveURL(/#\/components\/graph$/)
  await expect(page.getByRole('heading', { name: 'Graph and Timeline' })).toBeVisible()
})

test('Workspace docs keep layout, search, selection, and queue intent with the host', async ({ page }) => {
  await page.goto('/#/components/workspace')
  await expect(page.locator('[data-tint-workspace-grid]')).toBeVisible()
  await page.getByRole('button', { name: 'Workspace item metrics', exact: true }).focus()
  await page.keyboard.press('Alt+ArrowRight')
  await expect(page.getByText('Metric panel x: 1 · Revision: 2')).toBeVisible()
  await page.getByRole('searchbox', { name: 'Search', exact: true }).fill('Atlas')
  await expect(page.getByRole('table', { name: 'Available releases' })).toContainText('Bright Atlas')
  await expect(page.getByRole('table', { name: 'Available releases' })).not.toContainText('River Echo')
  await page.getByRole('checkbox', { name: /Bright Atlas/ }).check()
  await page.getByRole('button', { name: 'Add 1 to preview queue' }).click()
  await expect(page.getByText('Queue preview: atlas')).toBeVisible()
})

test('Chat docs keep messages, tool decisions, composer, and preferences host controlled', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/#/components/chat')
  await expect(page.getByRole('heading', { name: 'Chat', exact: true })).toBeVisible()
  const log = page.getByRole('log', { name: 'Messages' })
  await expect(log).toHaveAttribute('aria-live', 'off')
  await expect(log.locator('[data-chat-part="markdown"]')).toContainText('Send a message')
  await log.getByRole('button', { name: 'Load earlier messages' }).click()
  await expect(log).toContainText('An earlier message preserved')

  await log.getByRole('textbox', { name: 'Optional note' }).fill('Looks safe')
  await log.getByRole('button', { name: 'Approve' }).click()
  await expect(log.getByText('Approved', { exact: true })).toBeVisible()
  await expect(page.getByText('Last intent: Approved run-demo: Looks safe')).toBeVisible()

  const composer = page.locator('[data-chat-composer]')
  await composer.getByRole('textbox').fill('Hello from browser')
  await composer.getByRole('button', { name: 'Send message' }).click()
  await expect(log).toContainText('Hello from browser')
  await expect(composer.getByRole('button', { name: 'Stop response' })).toBeVisible()
  await composer.getByRole('button', { name: 'Stop response' }).click()
  await expect(log.locator('[data-message-id="a-1"]')).toHaveAttribute('data-status', 'stopped')
  await log.locator('[data-message-id="a-1"]').getByRole('button', { name: 'Retry' }).click()
  await expect(log.locator('[data-message-id="a-1"]')).toContainText('The local response was retried.')

  const preference = page.locator('.preference-demo')
  await preference.getByRole('radio', { name: /Detailed response/ }).click()
  await expect(preference.getByText('Preference recorded')).toBeVisible()
  await expect(page.getByText('Last intent: Preference detailed selected')).toBeVisible()
  await expect(page.getByRole('heading', { name: 'API' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Accessibility' })).toBeVisible()
  expect(errors).toEqual([])
})

test('Roleplay form docs keep ordered edits and import intent with the host', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/#/components/roleplay-forms')
  await expect(page.getByRole('heading', { name: 'Roleplay Forms' })).toBeVisible()

  const group = page.getByRole('region', { name: 'Group editor example' })
  await group.getByRole('button', { name: 'Add member' }).click()
  await expect(group.getByRole('status')).toHaveText('Group members: aria, bea')
  await group.getByRole('button', { name: 'Move Bea up' }).click()
  await expect(group.getByRole('status')).toHaveText('Group members: bea, aria')
  await group.getByRole('combobox', { name: 'Character prompts' }).selectOption('1')
  await expect(group.getByRole('textbox', { name: 'Joined prompt prefix' })).toHaveValue('Conversation:')

  const persona = page.getByRole('region', { name: 'Persona editor example' })
  await persona.getByRole('combobox', { name: 'Description placement' }).selectOption('0')
  await expect(persona.getByRole('spinbutton', { name: 'Depth' })).toHaveCount(0)
  await expect(persona.getByRole('status')).toHaveText('Placement: 0')

  const regex = page.getByRole('region', { name: 'Regex editor example' })
  await regex.getByRole('button', { name: 'Add regex rule' }).click()
  await expect(regex.getByRole('status')).toHaveText('Rules: 2')

  const review = page.getByRole('region', { name: 'Import review example' })
  await expect(review.getByRole('table', { name: 'Import file coverage' })).toContainText('Chats')
  await review.getByRole('button', { name: 'Import 3 files' }).click()
  await expect(review.getByRole('status')).toHaveText('Import saved.')
  expect(errors).toEqual([])
})
