"""Generate the docs dependency graph from the real import graph.

Scans src/components/*/ for cross-component imports (e.g. media-player
importing from ../media) and emits src/docs/generated/docsGraph.ts as plain
data: one node per component directory, its sorted imports, and a deterministic
layered-grid position so the canvas needs no physics pass.

Run once; the output is committed as data. Everything is derived from sorted
directory listings and file contents, so the output is stable across runs and
reviewable as a diff.
"""
import pathlib, re, json

# Derived from this file's location, not hardcoded: the generator has to be
# runnable from any clone for its output to be reproducible in review.
ROOT = pathlib.Path(__file__).resolve().parent.parent
COMPONENTS = ROOT / 'src/components'
OUT = ROOT / 'src/docs/generated/docsGraph.ts'

IMPORT_RE = re.compile(r"""(?:from|import)\s*\(?\s*['"](\.[^'"]+)['"]""")

components = sorted(p.name for p in COMPONENTS.iterdir() if p.is_dir())

# Adjacency: component -> sorted list of sibling component dirs it imports.
# Test files and imports that stay inside the same component (../contracts from
# a graph subdirectory, say) are not dependency edges.
imports = {}
for comp in components:
    deps = set()
    for f in sorted((COMPONENTS / comp).rglob('*')):
        if f.suffix not in ('.ts', '.tsx') or '.test.' in f.name:
            continue
        for m in IMPORT_RE.finditer(f.read_text(errors='ignore')):
            target = (f.parent / m.group(1)).resolve()
            try:
                rel = target.relative_to(COMPONENTS)
            except ValueError:
                continue
            tcomp = rel.parts[0]
            if tcomp != comp and tcomp in components:
                deps.add(tcomp)
    imports[comp] = sorted(deps)

# Layered layout: a component's layer is the longest import chain below it, so
# foundations (icon) sit left and surfaces (media-player) right. Columns are
# alphabetically ordered and vertically centred.
layer_cache = {}
def layer(comp):
    if comp not in layer_cache:
        deps = imports[comp]
        layer_cache[comp] = 0 if not deps else 1 + max(layer(d) for d in deps)
    return layer_cache[comp]

positions = {}
by_layer = {}
for comp in components:
    by_layer.setdefault(layer(comp), []).append(comp)
COL_W, ROW_H = 340, 150
for lay, comps_in_layer in sorted(by_layer.items()):
    for i, comp in enumerate(comps_in_layer):
        positions[comp] = {
            'x': lay * COL_W,
            'y': int((i - (len(comps_in_layer) - 1) / 2) * ROW_H),
        }

lines = [
    '/*',
    ' * GENERATED by scripts/gen-docs-graph.py — do not edit by hand.',
    ' *',
    ' * The cross-component import graph of src/components, captured as plain data',
    ' * so the Dependency Graph docs page has no runtime scan step. Positions are a',
    ' * deterministic layered grid (a node\'s layer is the longest import chain',
    ' * below it), so the canvas renders without a physics pass.',
    ' *',
    ' * Regenerate with: python3 scripts/gen-docs-graph.py',
    ' */',
    '',
    'export type DocsGraphNode = {',
    '  /** Component directory under src/components. */',
    '  id: string',
    '  /** Sibling component directories this one imports, sorted. */',
    '  imports: readonly string[]',
    '  /** Deterministic layered-grid position. */',
    '  position: { x: number; y: number }',
    '}',
    '',
    'export const docsGraphNodes: readonly DocsGraphNode[] = [',
]
for comp in components:
    lines.append(
        '  { id: %s, imports: %s, position: %s },'
        % (
            json.dumps(comp),
            json.dumps(imports[comp]),
            json.dumps(positions[comp], separators=(', ', ': ')),
        )
    )
lines.append(']')
lines.append('')

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text('\n'.join(lines))
print(f'components: {len(components)}')
print(f'edges: {sum(len(d) for d in imports.values())}')
print(f'layers: {len(by_layer)}')
