"""Generate the Svelte component dependency graph from source imports.

The committed output contains one node per production Svelte component package,
plus the form package, with deterministic positions and no runtime source scan.
"""

import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
COMPONENTS = ROOT / 'src/svelte/components'
FORM = ROOT / 'src/svelte/form'
OUT = ROOT / 'src/docs/generated/docsGraph.ts'
IMPORT_RE = re.compile(r"""(?:from|import)\s*\(?\s*['"](\.[^'"]+)['"]""")

packages = {
    path.name: path
    for path in COMPONENTS.iterdir()
    if path.is_dir() and (path / 'index.ts').exists() and path.name != 'testing'
}
packages['form'] = FORM
names = sorted(packages)


def source_files(directory):
    for file in sorted(directory.rglob('*')):
        if file.suffix not in ('.ts', '.svelte'):
            continue
        if '.test.' in file.name or '.spec.' in file.name:
            continue
        if any(mark in file.name for mark in ('Fixture', 'Harness', 'Probe')):
            continue
        yield file


def package_for(path):
    for name, directory in packages.items():
        if path.is_relative_to(directory):
            return name
    return None


imports = {}
for name in names:
    dependencies = set()
    for file in source_files(packages[name]):
        for match in IMPORT_RE.finditer(file.read_text(errors='ignore')):
            dependency = package_for((file.parent / match.group(1)).resolve())
            if dependency and dependency != name:
                dependencies.add(dependency)
    imports[name] = sorted(dependencies)


layer_cache = {}


def layer(name, visiting=frozenset()):
    if name not in layer_cache:
        if name in visiting:
            return 0
        dependencies = imports[name]
        layer_cache[name] = 0 if not dependencies else 1 + max(
            layer(dependency, visiting | {name}) for dependency in dependencies
        )
    return layer_cache[name]


by_layer = {}
for name in names:
    by_layer.setdefault(layer(name), []).append(name)

positions = {}
for column, column_names in sorted(by_layer.items()):
    for row, name in enumerate(column_names):
        positions[name] = {
            'x': column * 340,
            'y': int((row - (len(column_names) - 1) / 2) * 150),
        }

lines = [
    '/*',
    ' * GENERATED by scripts/gen-docs-graph.py — do not edit by hand.',
    ' *',
    ' * Cross-package imports of src/svelte/components and src/svelte/form.',
    ' * Positions use a deterministic layered grid, so the canvas needs no',
    ' * runtime scan or physics pass.',
    ' *',
    ' * Regenerate with: python3 scripts/gen-docs-graph.py',
    ' */',
    '',
    'export type DocsGraphNode = {',
    '  /** Svelte component package directory, or form. */',
    '  id: string',
    '  /** Sibling packages this package imports, sorted. */',
    '  imports: readonly string[]',
    '  /** Deterministic layered-grid position. */',
    '  position: { x: number; y: number }',
    '}',
    '',
    'export const docsGraphNodes: readonly DocsGraphNode[] = [',
]
for name in names:
    lines.append(
        '  { id: %s, imports: %s, position: %s },'
        % (
            json.dumps(name),
            json.dumps(imports[name]),
            json.dumps(positions[name], separators=(', ', ': ')),
        )
    )
lines.extend([']', ''])

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text('\n'.join(lines))
print(f'components: {len(names)}')
print(f'edges: {sum(len(dependencies) for dependencies in imports.values())}')
print(f'layers: {len(by_layer)}')
